# Generated by Django 4.0 on 2021-12-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='size',
            new_name='nutritions',
        ),
        migrations.AlterModelTable(
            name='nutrition',
            table='nutrition',
        ),
    ]
