# Generated by Django 4.0 on 2021-12-11 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_size_drink_nutritions_alter_nutrition_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nutrition',
            table=None,
        ),
    ]
