# Generated by Django 4.0 on 2021-12-11 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_nutrition_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allergy',
            table='allergies',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='drink',
            table='drinks',
        ),
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menus',
        ),
        migrations.AlterModelTable(
            name='nutrition',
            table='nutritions',
        ),
        migrations.AlterModelTable(
            name='size',
            table='sizes',
        ),
    ]
