# Generated by Django 4.0 on 2021-12-11 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_allergy_table_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='caffeine_mg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.drink'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='one_serving_kcal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein_g',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='saturated_fat_g',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.size'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sodium_mg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sugars_g',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_fluid_ounce',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_ml',
            field=models.IntegerField(null=True),
        ),
    ]
