# Generated by Django 4.0 on 2021-12-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_image_url_alter_nutrition_caffeine_mg_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drink',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='drink',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='drink',
            new_name='Product',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
